from tkinter import *
window = Tk()
window.title('1114-2')
lab1 = Label(window,text="tab1",relief="raised")
lab2 = Label(window,text="tab2",relief="raised")
lab3 = Label(window,text="tab3",relief="raised")
lab4 = Label(window,text="tab4",relief="raised")
lab5 = Label(window,text="tab5",relief="raised")
lab6 = Label(window,text="tab6",relief="raised")
lab7 = Label(window,text="tab7",relief="raised")
lab8 = Label(window,text="tab8",relief="raised")
lab1.grid(row=0,column=0)
lab2.grid(row=0,column=1,rowspan=2)
lab3.grid(row=0,column=2,columnspan=2)
# lab4.grid(row=0,column=3)
lab5.grid(row=1,column=0)
# lab6.grid(row=1,column=1)
lab7.grid(row=1,column=2)
lab8.grid(row=1,column=3)
window.mainloop()