from tkinter import *
window = Tk()
window.title("1114_1")
lab1 = Label(window,text="hihihihihi",bg="lightyellow")
lab2 = Label(window,text="lorem text",bg="lightgreen")
lab3 = Label(window,text="hahahahahaha",bg="lightblue")
# lab1.pack(side=LEFT,fill=BOTH,expand=True)
# lab2.pack(fill=Y,expand=True)
# lab3.pack(pady=10,fill=Y,expand=True)
lab1.grid(row=0,column=0)
lab2.grid(row=1,column=0)
lab3.grid(row=1,column=1)
window.mainloop()